# Generated by Django 5.2.8 on 2025-11-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='agence',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poste',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typeprestation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
