# Generated by Django 5.2.8 on 2025-11-20 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0002_alter_user_managers_alter_agence_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('commentaire_arret', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agences.agence')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_offre_commercial', to=settings.AUTH_USER_MODEL)),
                ('prestations', models.ManyToManyField(to='Agences.typeprestation')),
                ('responsable_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_offre_ca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Appel d'offre",
                'verbose_name_plural': "Appels d'offre",
            },
        ),
    ]
