# Generated by Django 5.2.8 on 2025-11-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0003_appeloffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='couleur',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
