# Generated by Django 5.2.8 on 2025-11-20 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0004_agence_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='agence_terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_terrain', to='Agences.agence'),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='agence_traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_traitement', to='Agences.agence'),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='commentaire_fin_terrain',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='commentaire_fin_traitement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='commentaire_prod_mada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='commentaire_reprise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_debut_prod_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_debut_terrain',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_debut_terrain_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_debut_traitement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_debut_traitement_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_envoi_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_prevue_prod_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_prevue_reprise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_prevue_terrain',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_prevue_traitement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_reelle_prod_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_reelle_reprise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_terrain_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_traitement_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_livraison_prevue_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_livraison_reelle_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_reprise_france',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='etape_envoi_mada',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='etape_prod_mada',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='etape_reprise_france',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='etape_terrain_france',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='etape_traitement_france',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='info_supplementaire_mada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='nom_affaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='nom_affaire_traitement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='responsable_prod_terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_prod_terrain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='responsable_prod_traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_prod_traitement', to=settings.AUTH_USER_MODEL),
        ),
    ]
