# Generated by Django 5.2.8 on 2025-11-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0005_appeloffre_agence_terrain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeloffre',
            old_name='commentaire_prod_mada',
            new_name='commentaire_fin_prod_mada',
        ),
        migrations.RenameField(
            model_name='appeloffre',
            old_name='commentaire_reprise',
            new_name='commentaire_fin_reprise',
        ),
        migrations.RenameField(
            model_name='appeloffre',
            old_name='date_fin_reelle_prod_mada',
            new_name='date_debut_reprise',
        ),
        migrations.RenameField(
            model_name='appeloffre',
            old_name='date_fin_reelle_reprise',
            new_name='date_fin_prod_mada_reelle',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_reprise_france',
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_fin_reprise_reelle',
            field=models.DateField(blank=True, null=True),
        ),
    ]
