# Generated by Django 5.2.8 on 2025-11-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0006_rename_commentaire_prod_mada_appeloffre_commentaire_fin_prod_mada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffreCAAOGagne',
            fields=[
            ],
            options={
                'verbose_name': 'AO CA - AO Gagné',
                'verbose_name_plural': 'AO CA - AO Gagné',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCAEnvoiMada',
            fields=[
            ],
            options={
                'verbose_name': 'AO CA - Envoi Mada',
                'verbose_name_plural': 'AO CA - Envoi Mada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCAProdMada',
            fields=[
            ],
            options={
                'verbose_name': 'AO CA - Prod Mada',
                'verbose_name_plural': 'AO CA - Prod Mada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCARepriseFrance',
            fields=[
            ],
            options={
                'verbose_name': 'AO CA - Reprise France',
                'verbose_name_plural': 'AO CA - Reprise France',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCATermine',
            fields=[
            ],
            options={
                'verbose_name': 'AO CA - Terminé',
                'verbose_name_plural': 'AO CA - Terminé',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCATerrainFrance',
            fields=[
            ],
            options={
                'verbose_name': 'AO CA - Terrain France',
                'verbose_name_plural': 'AO CA - Terrain France',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCATraitementFrance',
            fields=[
            ],
            options={
                'verbose_name': 'AO CA - Traitement France',
                'verbose_name_plural': 'AO CA - Traitement France',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCommercialEnAttente',
            fields=[
            ],
            options={
                'verbose_name': 'AO Commercial - En Attente',
                'verbose_name_plural': 'AO Commercial - En Attente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCommercialEnCours',
            fields=[
            ],
            options={
                'verbose_name': 'AO Commercial - En Cours',
                'verbose_name_plural': 'AO Commercial - En Cours',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCommercialGagne',
            fields=[
            ],
            options={
                'verbose_name': 'AO Commercial - Gagné',
                'verbose_name_plural': 'AO Commercial - Gagné',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreCommercialPerdu',
            fields=[
            ],
            options={
                'verbose_name': 'AO Commercial - Perdu',
                'verbose_name_plural': 'AO Commercial - Perdu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
    ]
