# Generated by Django 5.2.8 on 2025-11-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0008_delete_appeloffrecatermine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffrecaaogagne',
            options={'verbose_name': 'AO CA - 1 - AO Gagné', 'verbose_name_plural': 'AO CA - 1 - AO Gagné'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecaenvoimada',
            options={'verbose_name': 'AO CA - 4 - Envoi Mada', 'verbose_name_plural': 'AO CA - 4 - Envoi Mada'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecaprodmada',
            options={'verbose_name': 'AO CA - 6 - Prod Mada', 'verbose_name_plural': 'AO CA - 6 - Prod Mada'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecareprisefrance',
            options={'verbose_name': 'AO CA - 5 - Reprise France', 'verbose_name_plural': 'AO CA - 5 - Reprise France'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecaterrainfrance',
            options={'verbose_name': 'AO CA - 2 - Terrain France', 'verbose_name_plural': 'AO CA - 2 - Terrain France'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecatraitementfrance',
            options={'verbose_name': 'AO CA - 3 - Traitement France', 'verbose_name_plural': 'AO CA - 3 - Traitement France'},
        ),
    ]
