# Generated by Django 5.2.8 on 2025-11-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0009_alter_appeloffrecaaogagne_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffrecommercialenattente',
            options={'verbose_name': 'AO Commercial - 1 - En Attente', 'verbose_name_plural': 'AO Commercial - 1 - En Attente'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecommercialencours',
            options={'verbose_name': 'AO Commercial - 2 - En Cours', 'verbose_name_plural': 'AO Commercial - 2 - En Cours'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecommercialgagne',
            options={'verbose_name': 'AO Commercial - 3 - Gagné', 'verbose_name_plural': 'AO Commercial - 3 - Gagné'},
        ),
        migrations.AlterModelOptions(
            name='appeloffrecommercialperdu',
            options={'verbose_name': 'AO Commercial - 4 - Perdu', 'verbose_name_plural': 'AO Commercial - 4 - Perdu'},
        ),
    ]
