# Generated by Django 5.2.8 on 2025-11-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0010_alter_appeloffrecommercialenattente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_debut_terrain_reelle',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_debut_traitement_reelle',
        ),
    ]
