# Generated by Django 5.2.8 on 2025-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0011_remove_appeloffre_date_debut_terrain_reelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='date_reception_france',
            field=models.DateField(blank=True, null=True),
        ),
    ]
