# Generated by Django 5.2.8 on 2025-11-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0012_appeloffre_date_reception_france'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffreProdComplement',
            fields=[
            ],
            options={
                'verbose_name': 'PROD - Compléments',
                'verbose_name_plural': 'PROD - Compléments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreProdEnCoursMada',
            fields=[
            ],
            options={
                'verbose_name': 'PROD - 3 - Prod Mada en cours',
                'verbose_name_plural': 'PROD - 3 - Prod Mada en cours',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreProdReceptionFrance',
            fields=[
            ],
            options={
                'verbose_name': 'PROD - 1 - Réception France',
                'verbose_name_plural': 'PROD - 1 - Réception France',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreProdRepriseFrance',
            fields=[
            ],
            options={
                'verbose_name': 'PROD - 2 - Reprise France',
                'verbose_name_plural': 'PROD - 2 - Reprise France',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
        migrations.CreateModel(
            name='AppelOffreProdTermine',
            fields=[
            ],
            options={
                'verbose_name': 'PROD - 4 - Production terminée',
                'verbose_name_plural': 'PROD - 4 - Production terminée',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Agences.appeloffre',),
        ),
    ]
