# Generated by Django 5.2.8 on 2025-11-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0013_appeloffreprodcomplement_appeloffreprodencoursmada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeloffreprodcomplement',
            options={'verbose_name': 'AO - PROD - Compléments', 'verbose_name_plural': 'AO - PROD - Compléments'},
        ),
        migrations.AlterModelOptions(
            name='appeloffreprodencoursmada',
            options={'verbose_name': 'AO - PROD - 3 - Prod Mada en cours', 'verbose_name_plural': 'AO - PROD - 3 - Prod Mada en cours'},
        ),
        migrations.AlterModelOptions(
            name='appeloffreprodreceptionfrance',
            options={'verbose_name': 'AO - PROD - 1 - Réception France', 'verbose_name_plural': 'AO - PROD - 1 - Réception France'},
        ),
        migrations.AlterModelOptions(
            name='appeloffreprodreprisefrance',
            options={'verbose_name': 'AO - PROD - 2 - Reprise France', 'verbose_name_plural': 'AO - PROD - 2 - Reprise France'},
        ),
        migrations.AlterModelOptions(
            name='appeloffreprodtermine',
            options={'verbose_name': 'AO - PROD - 4 - Production terminée', 'verbose_name_plural': 'AO - PROD - 4 - Production terminée'},
        ),
    ]
