# Generated by Django 5.2.8 on 2025-11-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0015_alter_appeloffreprodcomplement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='date_envoi_2_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_envoi_3_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_envoi_4_mada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='probleme_reception_ack',
            field=models.BooleanField(default=False),
        ),
    ]
