# Generated by Django 5.2.8 on 2025-11-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0016_appeloffre_date_envoi_2_mada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_envoi_2_mada',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_envoi_3_mada',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='date_envoi_4_mada',
        ),
        migrations.RemoveField(
            model_name='appeloffre',
            name='probleme_reception_ack',
        ),
    ]
