# Generated by Django 5.2.8 on 2025-11-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0017_remove_appeloffre_date_envoi_2_mada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='probleme_confirme',
            field=models.BooleanField(default=False),
        ),
    ]
