# Generated by Django 5.2.8 on 2025-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agences', '0018_appeloffre_probleme_confirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='historique_commentaires',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
